---
#####################################    
- name: Deploy service configuration
#####################################  
  hosts: ios-pe
  tags:
    - deploy-services-pe
  gather_facts: false
  connection: local
  vars_files:
    - ~/secure/passwords
  tasks:
  - name: Deploy service config for IOS using NAPALM
    napalm_install_config:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_ssh_user }}"
      dev_os: "{{ ansible_device_os }}"
      password: "{{ ansible_ssh_pass }}"
      config_file: "./generated_config/{{inventory_hostname}}/services/{{inventory_hostname}}.ios-services.cfg"
      #commit_changes: "{{commit}}"
      commit_changes: "{{ not ansible_check_mode }}"
      replace_config: false
      #diff_file: "./diff.txt"
      get_diffs: true
    register: output  
  - debug: var=output    