---
##################################################
- name: File and directory changes on localhost 
##################################################
  hosts: localhost
  connection: local
  vars:
    output: printouts
  tasks:
    - name: Create directory on local file system
      local_action: file path={{output}} state=directory
      run_once: true

##################################################
- name: Show version and other user level commands
##################################################
  hosts: ios
  gather_facts: false
  vars:
    output: printouts
  vars_files:
    - ~/secure/passwords
    - "./ios/commands.yml"
  connection: local
 
  tasks:
  - name: run multiple commands on remote nodes
    ios_command:
      commands:
        - show ip int brief
        - "{{show_arp}}"
        - sh capability feature routing 

    register: show
# - debug: var=show.stdout_lines
  
  - name: Save output in files  
    local_action: copy content={{show.stdout | to_nice_json}} dest={{output}}/{{inventory_hostname}}.report.txt  

#################################################
- name: GET snmp interface facts printed to JSON
#################################################
  hosts: ios
  gather_facts: false
  vars:
    output: printouts
  vars_files:
    - ~/secure/passwords
  connection: local
 
  tasks:
  - snmp_facts:
      host: "{{ansible_host}}"
      version: v2
      community: "{{snmp_community}}"
    register: snmpresult
  - debug: var=snmpresult.ansible_facts

  - name: Save output in files  
    local_action: copy content={{snmpresult.ansible_facts.ansible_interfaces | to_nice_json}} dest={{output}}/{{inventory_hostname}}.snmpreport.json 
  








 


 
