---
##################################################
- name: File and directory changes on localhost 
##################################################
  hosts: localhost
  connection: local
  vars:
    output: printouts
  tasks:
    - name: Create directory on local file system
      local_action: file path={{output}} state=directory
      run_once: true

##################################################
- name: Gather IOS facts
##################################################
  hosts: all
  vars:
    output: printouts
  vars_files:
    - ~/secure/passwords
  connection: local
 
  tasks:
  - name: run multiple commands on remote nodes
    snmp_facts:
      host: "{{ansible_host}}"
      version: v2
      community: "{{snmp_community}}"
  
  - name: Save output in files  
    local_action: copy content={{hostvars[inventory_hostname]|to_nice_yaml(indent=4)}} dest={{output}}/{{inventory_hostname}}.yml